# memory_folder: ./src/database/memory
# conversation: ./src/database/conversation/conversation.pkl

redis:
  auth: zxy@blog
  ip: 81.70.43.189
  port: 6379
  db: 0

mysql:
  ip: 81.70.43.189
  port: 3306
  db: erp
  user: blog
  passwd: Zxy@020206
